"
" This file was automatically generated by riml 0.2.9
" Modify with care!
"
 
" included: 'shape.riml'
function! g:ShapeConstructor()
  let shapeObj = {}
  let shapeObj.is_shape = 1
  let shapeObj.to_s = function('g:Shape_to_s')
  return shapeObj
endfunction

function! g:Shape_to_s() dict
  return 'Shape'
endfunction

 
" included: 'rectangle.riml'
function! g:RectangleConstructor(width, height)
  let rectangleObj = {}
  let shapeObj = g:ShapeConstructor()
  call extend(rectangleObj, shapeObj)
  let rectangleObj.width = a:width
  let rectangleObj.height = a:height
  let rectangleObj.to_s = function('g:Rectangle_to_s')
  return rectangleObj
endfunction

function! g:Rectangle_to_s() dict
  return "Rectangle(" . self.width . "x" . self.height . ")"
endfunction

function! s:main()
  let rectangle = g:RectangleConstructor(10, 10)
  echomsg rectangle.to_s()
endfunction

call s:main()
